# Generated by Django 5.2.7 on 2025-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dateJoined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='fName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_super_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastLogin',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
