# Generated by Django 5.2.7 on 2025-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='images/categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['categoryName'],
            },
        ),
    ]
